<a href="https://colab.research.google.com/github/gameqube963741/practice_for_nlp/blob/master/NLP_text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
news = '''
台灣米其林與 PChome 雙領導品牌聯手開發了全台首個「一鍵式輪胎電商銷售機制」，即將讓 O2O 購胎平台進入真正的「全自動時代」。
PChome「米其林馳加旗艦館」於 2019 年中正式上線，台灣米其林隨即啟動蒐集廣大用戶的意見，並從中了解到電商消費者在網上購買輪胎時，除了價格外，更重視購胎操作的便利性與時間安排的彈性。根據調查，在現今的電商購胎環境下，消費者仍須按地區前往相對應賣場購買輪胎，並等候客服人員聯絡，方能預約安裝時間。一來一往的流程降低了電商購胎的操作便利性與購買友善度。因此，台灣米其林與 PChome 聯手，推出全新一鍵式輪胎電商銷售機制。
PChome「米其林馳加旗艦館」將於 2020 年 10 月 1 日正式導入一鍵式銷售機制，全面轉換為真正的全自動 O2O 賣場，成為全台首個提供一鍵式購胎服務的電商平台。消費者於 PChome「米其林馳加旗艦館」購買輪胎時，僅須決定欲購買的胎款並選擇安裝店家與期望安裝時段，系統將自動配對資訊、完成預約，且透過簡訊發送確認訊息。全部購胎流程在同一頁面，一鍵完成，消費者無須被動等待客服人員聯絡，或擔心因為忙碌漏接電話。
除了推出全新電商銷售機制外，PChome「米其林馳加旗艦館」也同步祭出 10 月限量購胎折扣以及限定商品的好康優惠。10 月期間，購買精選胎款 Energy Saver 4 或 Pilot Sport 4 指定規格 4 入組（Energy Saver 4 185/55 R16；Pilot Sport 4 215/55 R17）就有機會享 95 折好康優惠，限量十組，要買要快。此外，10 月 1 日至 10 月 25 日，購買輪胎 4 入組（不含輕卡胎）即可將米其林寶寶限量版玩偶帶回家；剛發布的《臺北臺中米其林指南 2020》現在更有機會以獨家珍藏價 650 元購得。限量 11 組優惠價。
'''

# 正規表達法斷句

In [2]:
import re
re.split('，|：|、|「|」',news)

['\n台灣米其林與 PChome 雙領導品牌聯手開發了全台首個',
 '一鍵式輪胎電商銷售機制',
 '',
 '即將讓 O2O 購胎平台進入真正的',
 '全自動時代',
 '。\nPChome',
 '米其林馳加旗艦館',
 '於 2019 年中正式上線',
 '台灣米其林隨即啟動蒐集廣大用戶的意見',
 '並從中了解到電商消費者在網上購買輪胎時',
 '除了價格外',
 '更重視購胎操作的便利性與時間安排的彈性。根據調查',
 '在現今的電商購胎環境下',
 '消費者仍須按地區前往相對應賣場購買輪胎',
 '並等候客服人員聯絡',
 '方能預約安裝時間。一來一往的流程降低了電商購胎的操作便利性與購買友善度。因此',
 '台灣米其林與 PChome 聯手',
 '推出全新一鍵式輪胎電商銷售機制。\nPChome',
 '米其林馳加旗艦館',
 '將於 2020 年 10 月 1 日正式導入一鍵式銷售機制',
 '全面轉換為真正的全自動 O2O 賣場',
 '成為全台首個提供一鍵式購胎服務的電商平台。消費者於 PChome',
 '米其林馳加旗艦館',
 '購買輪胎時',
 '僅須決定欲購買的胎款並選擇安裝店家與期望安裝時段',
 '系統將自動配對資訊',
 '完成預約',
 '且透過簡訊發送確認訊息。全部購胎流程在同一頁面',
 '一鍵完成',
 '消費者無須被動等待客服人員聯絡',
 '或擔心因為忙碌漏接電話。\n除了推出全新電商銷售機制外',
 'PChome',
 '米其林馳加旗艦館',
 '也同步祭出 10 月限量購胎折扣以及限定商品的好康優惠。10 月期間',
 '購買精選胎款 Energy Saver 4 或 Pilot Sport 4 指定規格 4 入組（Energy Saver 4 185/55 R16；Pilot Sport 4 215/55 R17）就有機會享 95 折好康優惠',
 '限量十組',
 '要買要快。此外',
 '10 月 1 日至 10 月 25 日',
 '購買輪胎 4 入組（不含輕卡胎）即可將米其林寶寶限量版玩偶帶回家；剛發布的《臺北臺中米其林指南 2020》現在更有機會以獨家珍藏價 650 元購得。限量 11 組優惠價。\n']

# 安裝 jieba 套件

In [3]:
# ! pipenv/pip install jieba

In [4]:
import jieba
s = "大巨蛋案對市府同仁下封口令？　柯P否認"
seg = jieba.cut(s)

In [5]:
seg

<generator object Tokenizer.cut at 0x7efd356a24c0>

In [6]:
list(seg)

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.853 seconds.
Prefix dict has been built successfully.


['大', '巨蛋', '案對', '市府', '同仁', '下', '封口令', '？', '\u3000', '柯', 'P', '否認']

In [7]:
import jieba
s = "大巨蛋案對市府同仁下封口令？　柯P否認"
# 全模式
seg = jieba.cut(s, cut_all=True)
print(list(seg))

['大', '巨蛋', '案', '對', '市府', '同仁', '下', '封口', '封口令', '口令', '？', '\u3000', '', '柯', 'P', '否', '認']


# 處理英文資料 (NLTK)

In [8]:
#!pipenv/pip install nltk
!pip install nltk

In [9]:
import nltk
nltk.download('punkt')
sentence = "At eight o'clock on Thursday morning Arthur didn't feel very good"
tags = nltk.word_tokenize(sentence)
tags

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['At',
 'eight',
 "o'clock",
 'on',
 'Thursday',
 'morning',
 'Arthur',
 'did',
 "n't",
 'feel',
 'very',
 'good']

In [10]:
nltk.download('averaged_perceptron_tagger')
tagged = nltk.pos_tag(tags)
tagged

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


[('At', 'IN'),
 ('eight', 'CD'),
 ("o'clock", 'NN'),
 ('on', 'IN'),
 ('Thursday', 'NNP'),
 ('morning', 'NN'),
 ('Arthur', 'NNP'),
 ('did', 'VBD'),
 ("n't", 'RB'),
 ('feel', 'VB'),
 ('very', 'RB'),
 ('good', 'JJ')]

In [11]:
import nltk.stem
s= nltk.stem.SnowballStemmer('english')
print(s.stem("graphics"))

print(s.stem("imaging"))
print(s.stem("image"))
print(s.stem("imagination"))
print(s.stem("imagine"))

graphic
imag
imag
imagin
imagin


In [12]:
from nltk.corpus import stopwords
nltk.download('stopwords')
sw = stopwords.words('english')
sw

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

# 使用Jieba 斷詞

In [13]:
import jieba
s = "大巨蛋案對市府同仁下封口令？　柯P否認"
# 全模式
seg = jieba.cut(s, cut_all=True)
print(list(seg))

['大', '巨蛋', '案', '對', '市府', '同仁', '下', '封口', '封口令', '口令', '？', '\u3000', '', '柯', 'P', '否', '認']


In [14]:
# 精準模式
seg = jieba.cut(s)
print(list(seg))

['大', '巨蛋', '案對', '市府', '同仁', '下', '封口令', '？', '\u3000', '柯', 'P', '否認']


In [15]:
jieba.load_userdict('userdict.txt')
seg = jieba.cut(s)
print(list(seg))

['大巨蛋案', '對', '市府同仁', '下', '封口令', '？', '\u3000', '柯P', '否認']


In [16]:
import jieba.posseg as pseg
words = pseg.cut(s)

In [17]:
list(words)

[pair('大巨蛋案', 'x'),
 pair('對', 'x'),
 pair('市府同仁', 'x'),
 pair('下', 'f'),
 pair('封口令', 'n'),
 pair('？', 'x'),
 pair('\u3000', 'x'),
 pair('柯P', 'x'),
 pair('否認', 'v')]

In [18]:
words = jieba.tokenize(s)
for tw in words:
  print(tw[0], tw[1], tw[2])

大巨蛋案 0 4
對 4 5
市府同仁 5 9
下 9 10
封口令 10 13
？ 13 14
　 14 15
柯P 15 17
否認 17 19


# 使用網路爬蟲抓取自由時報關鍵字

In [19]:
import requests
from bs4 import BeautifulSoup
res = requests.get('https://news.ltn.com.tw/news/life/breakingnews/3308917')
soup = BeautifulSoup(res.text, 'lxml')
with open('userdict.txt', 'a', encoding='utf-8') as f:
    f.write('\n')
    for rec in soup.select('.keyword a'):
        f.write(rec.text+'\n')

# 切分n-gram

In [20]:
s = '那我們酸民婉君也可以報名嗎?'
s[0:2]

'那我'

In [21]:
s[1:3]

'我們'

In [22]:
s[len(s) - 2: len(s)]

'嗎?'

In [23]:
# bi-gram: 2-gram
for i in range(0, len(s) - 2 + 1):
    print(s[i:i+2])

那我
我們
們酸
酸民
民婉
婉君
君也
也可
可以
以報
報名
名嗎
嗎?


In [24]:
# tri-gram: 3-trim
for i in range(0, len(s) - 3 + 1):
    print(s[i:i+3])

那我們
我們酸
們酸民
酸民婉
民婉君
婉君也
君也可
也可以
可以報
以報名
報名嗎
名嗎?


In [25]:
def ngram(input_sentence, n = 2):
    ret = []
    for i in range(0, len(input_sentence) - n + 1):
        ret.append(input_sentence[i:i+n])
    return ret

In [26]:
s

'那我們酸民婉君也可以報名嗎?'

In [27]:
ngram(s, 2)

['那我', '我們', '們酸', '酸民', '民婉', '婉君', '君也', '也可', '可以', '以報', '報名', '名嗎', '嗎?']

In [28]:
ngram(s, n = 3)

['那我們',
 '我們酸',
 '們酸民',
 '酸民婉',
 '民婉君',
 '婉君也',
 '君也可',
 '也可以',
 '可以報',
 '以報名',
 '報名嗎',
 '名嗎?']

In [29]:
news = '''
釩泰研究創新公司違法委託未領有製造醫療用口罩許可證的丞威公司代製醫用口罩，已有170萬片流入市面，釩泰總經理李國鈺今天出面向大眾鞠躬掉淚致歉，他說，長期外銷醫療器材，今年9月加入國家隊、開始製口醫用口罩，對相關藥事法令不熟悉，認為長期合作的丞威已有製造業藥商許可執照，才會委託製造，對此事感到抱歉，會全面配合調查、並全力負責消費者退貨，也懇請政府能輔導相關法令，以免廠商誤觸法令，能以輔導取代處罰，讓中小企業持續為國人服務。李國鈺今天中午對外說明，並向社會大眾數度鞠躬致歉，他哽咽掉淚說，因為訂單壓力，委託丞威製造口罩，之前也去丞威廠勘，了解製造環境合格，由釩泰提供台灣國產熔噴布、內外層不織布、耳帶、鼻樑條等全部合格材料，再技術人員監工委託代工，成品再送回來確效並經第三方檢驗等測試，經品質驗收合格，才包裝、掛釩泰品牌，出貨給經銷商，他強調，該生產口罩均通過國家標準CNS14774測試，除使用合格材料外，並持續作最終品質認定方可出貨。
李國鈺說，在程序上、藥事法認定上造成的瑕疵與爭議，若有產生疏失導致消費者及經銷商的不安，甚感抱歉，日後在品質及製程將更加嚴謹把關，他也向他日夜加班疲累工作的工作同仁感謝，他也說，彰化口罩工廠多，大約有95％中小企業像他一樣天天埋頭生產、提升品質，不懂藥事法，希望政府能在法律上多加輔導。
他說，在今年8月通過第一等醫療器材許可證，核准製造醫用口罩，9月加入國家隊，雖然本身是洗腎過濾器國內最大廠商，但是新手製造口罩不熟悉，產量未如預期，礙於經銷商訂單的壓力，於是委託丞威製造口罩，從9月初到10月預計交900萬片，但丞威生產也不順利，交170多萬片，他也說，其實委託丞威的成本要3元到3.4元，比釩泰自己生產要2元上下還多。李國鈺說，釩泰加入國家隊，目前日產3萬到7萬片，原預定9月30日要交20萬片，目前也停止供貨。
'''

In [30]:
words = ngram(news, 2)

# 使用字典的方式統計語句

In [31]:
dic = {}
for w in words:
    if w not in dic:
        dic[w] = 1
    else:
        dic[w] = dic[w] + 1

In [32]:
import operator
swd = sorted(dic.items(), key = operator.itemgetter(1), reverse=True)
swd[1:10]

[('製造', 8),
 ('丞威', 7),
 ('說，', 7),
 ('釩泰', 6),
 ('委託', 6),
 ('，他', 6),
 ('罩，', 5),
 ('萬片', 5),
 ('用口', 4)]

In [33]:
words = ngram(news,3)

In [34]:
dic = {}
for w in words:
  if w not in dic:
    dic[w] = 1
  else:
    dic[w] = dic[w] + 1

In [35]:
import operator
swd = sorted(dic.items(), key = operator.itemgetter(1), reverse=True)
swd[1:10]

[('用口罩', 4),
 ('李國鈺', 4),
 ('萬片，', 4),
 ('醫用口', 3),
 ('0萬片', 3),
 ('加入國', 3),
 ('入國家', 3),
 ('國家隊', 3),
 ('藥事法', 3)]

In [36]:
a = [1,2,3,2,2,1]
dic2 = {}
for l in a:
    if l not in dic2:
        dic2[l] = 1
    else:
        dic2[l] = dic2[l] + 1
dic2

{1: 2, 2: 3, 3: 1}

# 利用counter統計詞頻

In [37]:
from collections import Counter
a = [1,1,1,3,5,7,8,8,9,9,]
c = Counter(a)
c

Counter({1: 3, 3: 1, 5: 1, 7: 1, 8: 2, 9: 2})

In [38]:
c.most_common(3)

[(1, 3), (8, 2), (9, 2)]

In [39]:
words = ngram(news,3)
c = Counter(words)
c.most_common(10)

[('口罩，', 5),
 ('用口罩', 4),
 ('李國鈺', 4),
 ('萬片，', 4),
 ('醫用口', 3),
 ('0萬片', 3),
 ('加入國', 3),
 ('入國家', 3),
 ('國家隊', 3),
 ('藥事法', 3)]

In [40]:
words = ngram(news,4)
c = Counter(words)
c.most_common(10)

[('醫用口罩', 3),
 ('用口罩，', 3),
 ('加入國家', 3),
 ('入國家隊', 3),
 ('委託丞威', 3),
 ('製造口罩', 3),
 ('李國鈺今', 2),
 ('國鈺今天', 2),
 ('致歉，他', 2),
 ('醫療器材', 2)]

In [41]:
words = ngram(news,2)
c = Counter(words)
c.most_common(10)

[('口罩', 9),
 ('製造', 8),
 ('丞威', 7),
 ('說，', 7),
 ('釩泰', 6),
 ('委託', 6),
 ('，他', 6),
 ('罩，', 5),
 ('萬片', 5),
 ('用口', 4)]

# 長詞優先法

In [42]:
import re 
sentenceAry = re.split('，|。|（|）|〕|〔|／|《|》|、|」|！|「|：',news)

In [43]:
#sentenceAry

In [44]:
a = '比特幣期貨 美核准上市'
a.replace('比特幣', '')

'期貨 美核准上市'

In [45]:
def removeKey(text, keywords):
    ret = text
    for word in keywords:
        ret = ret.replace(word, '')
    return ret

removeKey(a, ['比特幣', '核准', '期貨'])

' 美上市'

In [46]:
a = [1,2,3]
b = [2,3,4]
a.append(b)
a

[1, 2, 3, [2, 3, 4]]

In [47]:

a = [1,2,3]
b = [2,3,4]
a.extend(b)
a

[1, 2, 3, 2, 3, 4]

In [48]:
keywords = []

for n in range(4,1,-1):
    #print(n)
    words = []
    for sentence in sentenceAry:
        text_list = removeKey(sentence, keywords)
        words.extend(ngram(text_list, n))
    c = Counter(words)
    for word, cnt in c.items():
        if cnt >= 4:
            keywords.append(word)
keywords

['用口罩',
 '李國鈺',
 '釩泰',
 '委託',
 '製造',
 '丞威',
 '萬片',
 '9月',
 '國家',
 '口罩',
 '合格',
 '品質',
 '生產']

# 建立一長詞優先處理函數

In [49]:
news = '''
〔即時新聞／綜合報導〕台灣女星歐陽娜娜昨（30日）晚登上中國官媒央視，為十一國慶晚會獻唱被視為統戰歌曲的《我的祖國》，無獨有偶，先前曾多次表示「來自中國台灣」前WANNA ONE成員賴冠霖，今（1日）晚也將上央視國慶音樂會演唱《龍的傳人》，他近日在受訪影片中更以一口流利的北京腔說出：「我是賴冠霖，我在中國台灣等你！」綜合媒體報導，現年19歲、以韓國選秀節目《Produce 101 S2》出道的前Wanna One成員賴冠霖，自從團體解散後，就將演藝重心轉往中國，而在選秀期間就自稱來自中國台灣的他，今日也將出現在央視《江山如畫國慶音樂會》，並和其他中國藝人演唱《龍的傳人》。稍早央視也在微博PO出賴冠霖的個人宣傳片段，影片中他開頭就表示「我是賴冠霖，我在中國台北等你」，接著又強調「台灣省台北市」，還說有不少美食，鹽酥雞、鳳梨酥等等。昨晚歐陽娜娜登上央視國慶晚會，和中國藝人合唱《我的祖國》，引起軒然大波，陸委會也展開調查，若認定違規，將依《臺灣地區與大陸地區人民關係條例》開罰，最高恐罰50萬元。'''

In [50]:
import re
def longTermFirst(news, keywords, threshold):
    sentenceAry = re.split('，|。|（|）|〕|〔|／|《|》|、|」|！|「|：',news)

    for n in range(4,1,-1):
        words = []
        for sentence in sentenceAry:
            text_list = removeKey(sentence, keywords)
            words.extend(ngram(text_list, n))
            
        c = Counter(words)
        for word, cnt in c.items():
            m = re.match('^[\u4e00-\u9fa5]+$', word)
            if (cnt >= threshold) and m:
                keywords.append(word)
    return keywords

In [51]:
longTermFirst(news, [],3)

['中國台灣', '賴冠霖', '中國', '央視', '國慶']

# 使用正規表達法篩選中文字詞

In [52]:
words = ['中國台灣', '3/1', '\n \n',  '賴冠霖', '中國', '央視', '國慶']

import re
for w in words:
    m = re.match('^[\u4e00-\u9fa5]+$', w)
    if m:
        print(w)

中國台灣
賴冠霖
中國
央視
國慶


# 詞頻統計

In [53]:
article = '''
一、積極促進在投資和經濟合作領域加快給予台資企業與大陸企業同等待遇
1. 台灣同胞在大陸投資的企業 (以下簡稱「台資企業」) 參與「中國製造 2025」行動計劃適用與大陸企業同等政策。支持台商來大陸投資設立高端製造、智能製造、綠色製造等企業並設立區域總部和研發設計中心，相應享受稅收、投資等相關支持政策。

2. 幫助和支持符合條件的台資企業依法享受高新技術企業減按 15% 稅率徵收企業所得稅，研發費用加計扣除，設在大陸的研發中心採購大陸設備全額退還增值稅等稅收優惠政策。

3. 台灣科研機構、高等學校、企業在大陸註冊的獨立法人，可牽頭或參與國家重點研發計劃項目申報，享受與大陸科研機構、高等學校、企業同等政策。受聘於在大陸註冊的獨立法人的台灣地區科研人員，可作為國家重點研發計劃項目 (課題) 負責人申報，享受與大陸科研人員同等政策。對台灣地區知識產權在大陸轉化的，可參照執行大陸知識產權激勵政策。

4. 台資企業可以特許經營方式參與能源、交通、水利、環保、市政公用工程等基礎設施建設。

5. 台資企業可公平參與政府採購。

6. 台資企業可通過合資合作、併購重組等方式參與國有企業混合所有製改革。

7. 台資企業與大陸企業同等適用相關用地政策。對集約用地的鼓勵類台商投資工業項目優先供應土地，在確定土地出讓底價時，可按不低於所在地土地等別相對應大陸工業用地出讓最低價標準的 70% 執行。

8. 繼續在中西部、東北地區設立海峽兩岸產業合作區，鼓勵台資企業向中西部、東北地區轉移並參與「一帶一路」建設，拓展內需市場和國際市場。大力推進台商投資區和兩岸環保產業合作示範基地建設。

9. 台資農業企業可與大陸農業企業同等享受農機購置補貼、產業化重點龍頭企業等農業支持政策和優惠措施。

10. 台灣金融機構、商家可與中國銀聯及大陸非銀行支付機構依法合規開展合作，為台灣同胞提供便捷的小額支付服務。

11. 台灣徵信機構可與大陸徵信機構開展合作，為兩岸同胞和企業提供徵信服務。

12. 台資銀行可與大陸同業協作，通過銀團貸款等方式為實體經濟提供金融服務。

二、逐步為台灣同胞在大陸學習、創業、就業、生活提供與大陸同胞同等的待遇
13. 台灣同胞可報名參加 53 項專業技術人員職業資格考試和 81 項技能人員職業資格考試 (《向台灣居民開放的國家職業資格考試目錄》附後，具體執業辦法由有關部門另行製定)。

14. 台灣專業人才可申請參與國家「千人計劃」。在大陸工作的台灣專業人才，可申請參與國家「萬人計劃」。

15. 台灣同胞可申報國家自然科學基金、國家社會科學基金、國家傑出青年科學基金、國家藝術基金等各類基金項目。具體辦法由相關主管部門製定。

16. 鼓勵台灣同胞參與中華經典誦讀工程、文化遺產保護工程、非物質文化遺產傳承發展工程等中華優秀傳統文化傳承發展工程。支持台灣文化藝術界團體和人士參與大陸在海外舉辦的感知中國、中國文化年 (節)、歡樂春節等品牌活動，參加「中華文化走出去」計劃。符合條件的兩岸文化項目可納入海外中國文化中心項目資源庫。

17. 支持中華慈善獎、梅花獎、金鷹獎等經濟科技文化社會領域各類評獎項目提名涵蓋台灣地區。在大陸工作的台灣同胞可參加當地勞動模範、「五一」勞動獎章、技術能手、「三八」紅旗手等榮譽稱號評選。

18. 台灣人士參與大陸廣播電視節目和電影、電視劇製作可不受數量限制。

19. 大陸電影發行機構、廣播電視台、視聽網站和有線電視網引進台灣生產的電影、電視劇不做數量限制。

20. 放寬兩岸合拍電影、電視劇在主創人員比例、大陸元素、投資比例等方面的限制；取消收取兩岸電影合拍立項申報費用；縮短兩岸電視劇合拍立項階段故事梗概的審批時限。

21. 對台灣圖書進口業務建立綠色通道，簡化進口審批流程。同時段進口的台灣圖書可優先辦理相關手續。

22. 鼓勵台灣同胞加入大陸經濟、科技、文化、藝術類專業性社團組織、行業協會，參加相關活動。

23. 支持鼓勵兩岸教育文化科研機構開展中國文化、歷史、民族等領域研究和成果應用。

24. 台灣地區從事兩岸民間交流的機構可申請兩岸交流基金項目。

25. 鼓勵台灣同胞和相關社團參與大陸扶貧、支教、公益、社區建設等基層工作。

26. 在大陸高校就讀臨床醫學專業碩士學位的台灣學生，在參加研究生學習一年後，可按照大陸醫師資格考試報名的相關規定申請參加考試。

27. 取得大陸醫師資格證書的台灣同胞，可按照相關規定在大陸申請執業註冊。

28. 符合條件的台灣醫師，可通過認定方式獲得大陸醫師資格。符合條件的台灣醫師，可按照相關規定在大陸申請註冊短期行醫，期滿後可重新辦理註冊手續。

29. 在台灣已獲取相應資格的台灣同胞在大陸申請證券、期貨、基金從業資格時，只需通過大陸法律法規考試，無需參加專業知識考試。

30. 鼓勵台灣教師來大陸高校任教，其在台灣取得的學術成果可納入工作評價體系。

31. 為方便台灣同胞在大陸應聘工作，推動各類人事人才網站和企業線上招聘做好系統升級，支持使用台胞證註冊登錄。
'''

In [54]:
keywords = longTermFirst(article, ['大陸', '臺灣'], 5)

with open('userdict.txt', 'a', encoding='utf-8') as f:
    for w in keywords:
        f.write(w+'\n')

In [55]:
# unpacking
k, v = ('大陸', 38)
print(k)
print(v)

大陸
38


In [56]:
import jieba
from collections import Counter

jieba.load_userdict('userdict.txt')
c = Counter(list(jieba.cut(article)))
for k,v in c.most_common():
    if (len(k) >= 2) and (v >= 2):
        print(k,v)

大陸 38
台灣 15
台灣同胞 12
參與 12
文化 12
企業 10
兩岸 10
相關 9
機構 9
國家 9
台資企業 8
政策 8
支持 8
項目 8
資格 8
投資 7
鼓勵 7
參加 7
考試 7
申請 7
基金 7
電視 7
合作 6
中國 6
計劃 6
註冊 6
的台灣 6
地區 6
專業 6
企業同等 5
研發 5
享受 5
科研 5
人員 5
工程 5
工作 5
電影 5
醫師 5
經濟 4
符合 4
條件 4
申報 4
方式 4
建設 4
提供 4
領域 3
台商 3
中心 3
技術 3
重點 3
用地 3
土地 3
農業 3
開展 3
職業 3
人才 3
各類 3
中華 3
限制 3
合拍 3
按照 3
規定 3
待遇 2
適用 2
設立 2
相應 2
稅收 2
依法 2
費用 2
採購 2
優惠 2
高等 2
學校 2
立法 2
同等 2
知識產權 2
執行 2
工業 2
中西部 2
東北 2
台資 2
金融 2
支付 2
服務 2
徵信 2
同胞 2
學習 2
具體 2
執業 2
辦法 2
社會 2
發展 2
人士 2
海外 2
活動 2
可納入 2
科技 2
勞動 2
廣播 2
網站 2
比例 2
立項 2
審批 2
圖書 2
進口 2
辦理 2
手續 2
成果 2
交流 2
高校 2
取得 2


In [57]:
import scipy as sp
a, abb ,abc = ['a'], ['a', 'b', 'b'], ['a', 'b', 'c']
D = [a,abb,abc]

In [58]:
#tfidf('a', a, D)
tf  = 1/1
idf = sp.log(3/3)
tf * idf

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.log is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.0

In [59]:
#tfidf('a', abb, D)
tf  = 1/3
idf = sp.log(3/3)
tf * idf

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.log is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.0

In [60]:
#tfidf('a', abc, D)
tf  = 1/3
idf = sp.log(3/3)
tf * idf

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.log is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.0

In [61]:
#tfidf('b', abb, D)
tf  = 2/3
idf = sp.log(3/2)
tf * idf

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.log is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.27031007207210955

In [62]:
#tfidf('b', abc, D)
tf  = 1/3
idf = sp.log(3/2)
tf * idf

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.log is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.13515503603605478

In [63]:
#tfidf('c', abc, D)
tf  = 1/3
idf = sp.log(3/1)
tf * idf

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.log is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.3662040962227032

In [64]:
## count
a= [1,2,3,1,1,2]
a.count(1)

3

In [65]:
def tfidf(t,d,D):
    tf  = d.count(t) / len(d)
    idf = sp.log(len(D) / len([doc for doc in D if t in doc]) )
    return tf * idf

In [66]:
tfidf('a', a, D)
tfidf('a', abb, D)
tfidf('a', abc, D)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.log is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.0

In [67]:
tfidf('b', abb, D)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.log is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.27031007207210955

In [68]:
tfidf('b', abc, D)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.log is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.13515503603605478

In [69]:
tfidf('c', abc, D)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: scipy.log is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.log instead
  This is separate from the ipykernel package so we can avoid doing imports until


0.3662040962227032

In [70]:
import jieba.analyse
tags = jieba.analyse.extract_tags('那酸民婉君也可以報名嗎', 1)
tags

['那酸民婉君']

In [71]:
?jieba.analyse.set_idf_path

# 詞頻矩陣

In [72]:
## string join
s = ['a', 'v', 'g']
' '.join(s)
'@'.join(s)

'a@v@g'

In [73]:
corpus = ['this is a macbook', 'this is my iphone12']
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['iphone12', 'is', 'macbook', 'my', 'this']
[[0 1 1 0 1]
 [1 1 0 1 1]]


In [74]:
ary = ['【更新】柯P：洪智坤洩漏公文案還沒看到公文　今處理',
       '留洪智坤 柯：殘障求職不易',
       '人事處議處洪智坤　柯P：不清楚議處結果']

In [75]:
import jieba
jieba.load_userdict('userdict.txt')
corpus = []
for title in ary:
    corpus.append(' '.join(jieba.cut(title)) )
#jieba.cut()

In [76]:
corpus

['【 更新 】 柯P ： 洪智坤 洩漏 公文 案還 沒 看到 公文 \u3000 今處理',
 '留洪智坤   柯 ： 殘障 求職 不易',
 '人事 處議 處 洪智坤 \u3000 柯P ： 不 清楚 議處 結果']

In [77]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['不易', '人事', '今處理', '公文', '更新', '柯p', '案還', '殘障', '求職', '洩漏', '洪智坤', '清楚', '留洪智坤', '看到', '結果', '處議', '議處']
[[0 0 1 2 1 1 1 0 0 1 1 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 1 1 0 0 1 1 1]]


In [78]:
ary = ['【更新】柯P：洪智坤洩漏公文案還沒看到公文　今處理',
       '留洪智坤 柯文哲：殘障求職不易',
       '人事處議處洪智坤　柯P：不清楚議處結果']

In [79]:
import jieba
jieba.load_userdict('userdict.txt')
corpus = []
for title in ary:
    corpus.append(' '.join(jieba.cut(title)) )

In [80]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['不易', '人事', '今處理', '公文', '更新', '柯p', '柯文', '案還', '殘障', '求職', '洩漏', '洪智坤', '清楚', '留洪智坤', '看到', '結果', '處議', '議處']
[[0 0 1 2 1 1 0 1 0 0 1 1 0 0 1 0 0 0]
 [1 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 1]]


# 加入同義詞區分出一樣名詞

In [81]:
synonym = [w.strip() for w in  open('synonym.txt', 'r')]
synonym

['台灣/臺灣/Taiwan,', '川普/特郎普,', '柯文哲/柯p/柯P']

In [82]:
synonym_dic = {}
for term in synonym:
    words = term.split('/')
    for w in words:
        synonym_dic[w] = words[0]
synonym_dic

{'Taiwan,': '台灣',
 '台灣': '台灣',
 '川普': '川普',
 '柯P': '柯文哲',
 '柯p': '柯文哲',
 '柯文哲': '柯文哲',
 '特郎普,': '川普',
 '臺灣': '台灣'}

In [83]:
ary = ['【更新】柯P：洪智坤洩漏公文案還沒看到公文　今處理',
       '留洪智坤 柯文哲：殘障求職不易',
       '人事處議處洪智坤　柯P：不清楚議處結果']

In [84]:
s = '人事處議處洪智坤　柯P：不清楚議處結果'
[synonym_dic.get(w, w) for w in jieba.cut(s)]

['人事', '處議', '處', '洪智坤', '\u3000', '柯文哲', '：', '不', '清楚', '議處', '結果']

In [85]:
import jieba
jieba.load_userdict('userdict.txt')
corpus = []
for title in ary:
    #corpus.append(' '.join(jieba.cut(title)) )
    corpus.append(' '.join(\
        [synonym_dic.get(w, w) for w in jieba.cut(title)]) )
    

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['不易', '人事', '今處理', '公文', '更新', '柯文', '柯文哲', '案還', '殘障', '求職', '洩漏', '洪智坤', '清楚', '留洪智坤', '看到', '結果', '處議', '議處']
[[0 0 1 2 1 0 1 1 0 0 1 1 0 0 1 0 0 0]
 [1 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 1]]


# 留下白名單字詞

In [86]:
whilelist = ['市府', '柯文哲', '洪智坤']

In [87]:
import jieba
jieba.load_userdict('userdict.txt')
corpus = []
for title in ary:
    #corpus.append(' '.join(jieba.cut(title)) )
    corpus.append(' '.join(\
        [synonym_dic.get(w, w) for w in jieba.cut(title) \
         if synonym_dic.get(w, w) in whilelist]) )
    

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['柯文哲', '洪智坤']
[[1 1]
 [0 0]
 [1 1]]


# 設立停用字

In [88]:
stopwords = ['更新', '看到']
import jieba
jieba.load_userdict('userdict.txt')
corpus = []
for title in ary:
    #corpus.append(' '.join(jieba.cut(title)) )
    corpus.append(' '.join(\
        [synonym_dic.get(w, w) for w in jieba.cut(title) \
         if synonym_dic.get(w, w) not in stopwords]) )
    

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['不易', '人事', '今處理', '公文', '柯文', '柯文哲', '案還', '殘障', '求職', '洩漏', '洪智坤', '清楚', '留洪智坤', '結果', '處議', '議處']
[[0 0 1 2 0 1 1 0 0 1 1 0 0 0 0 0]
 [1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 1 0 0 0 0 1 1 0 1 1 1]]


# 計算出 TF-IDF 矩陣

In [89]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['不易', '人事', '今處理', '公文', '柯文', '柯文哲', '案還', '殘障', '求職', '洩漏', '洪智坤', '清楚', '留洪智坤', '結果', '處議', '議處']
[[0.         0.         0.35013871 0.70027741 0.         0.26628951
  0.35013871 0.         0.         0.35013871 0.26628951 0.
  0.         0.         0.         0.        ]
 [0.4472136  0.         0.         0.         0.4472136  0.
  0.         0.4472136  0.4472136  0.         0.         0.
  0.4472136  0.         0.         0.        ]
 [0.         0.40301621 0.         0.         0.         0.30650422
  0.         0.         0.         0.         0.30650422 0.40301621
  0.         0.40301621 0.40301621 0.40301621]]


# 計算文章的相似程度

In [90]:
ary = ['【更新】柯P：洪智坤洩漏公文案還沒看到公文　今處理',
       '留洪智坤 柯文哲：殘障求職不易',
       '人事處議處洪智坤　柯P：不清楚議處結果',
       '台北市市政顧問洪智坤，從選前就受到柯文哲信任重用，重金請來當市政顧問之後，在市政府的角色相當吃重，每天七點半的軍機處晨會不能沒有他，現在因為洩公文案，行動不便的洪智坤還坐著輪椅到議會備詢，人事處還要議處他']

In [91]:
stopwords = ['更新', '看到']
import jieba
jieba.load_userdict('userdict.txt')
corpus = []
for title in ary:
    #corpus.append(' '.join(jieba.cut(title)) )
    corpus.append(' '.join(\
        [synonym_dic.get(w, w) for w in jieba.cut(title) \
         if synonym_dic.get(w, w) not in stopwords]) )
    
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['七點', '不便', '不易', '不能', '人事', '今處理', '信任', '備詢', '公文', '受到', '台北市', '因為', '市政', '市政府', '柯文', '柯文哲', '案還', '椅到', '殘障', '每天', '求職', '沒有', '洩漏', '洪智坤', '清楚', '現在', '留洪智坤', '相當', '結果', '著輪', '處晨會', '處議', '行動', '角色', '請來當', '議會', '議處', '軍機', '選前', '還坐', '還要', '重用', '重金', '顧問']
[[0 0 0 0 0 1 0 0 2 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0
  1 0 0 0 0 0 0 0]
 [1 1 0 1 1 0 1 1 1 1 1 1 2 1 1 0 0 1 0 1 0 1 0 2 0 1 0 1 0 1 1 0 1 1 1 1
  1 1 1 1 1 1 1 2]]


In [92]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances(X)

array([[0.        , 3.74165739, 3.46410162, 6.55743852],
       [3.74165739, 0.        , 3.46410162, 6.70820393],
       [3.46410162, 3.46410162, 0.        , 6.40312424],
       [6.55743852, 6.70820393, 6.40312424, 0.        ]])

In [93]:
import numpy as np
import math
a = np.array([1,1,1,0,0,1])
b = np.array([1,1,0,0,1,1])
math.sqrt(sum((a - b) ** 2))

1.4142135623730951

# 計算Cosine相似度

In [94]:
from sklearn.metrics.pairwise import cosine_similarity
cs = cosine_similarity(X)

# 建立新聞推薦器(根據內容相似程度)

In [95]:
import pandas
news = pandas.read_excel('/content/news.xlsx')

In [96]:
news.head(10)

Unnamed: 0 category  ...              time                        title
0           0       娛樂  ...  2017年10月02日14:42   「鬼附身」入圍女配！許瑋甯開心到爆炸　柯佳嬿微鬱卒 
1           1       財經  ...  2017年10月02日14:38         半導體教父張忠謀　用30年打造台灣的驕傲
2           2       國際  ...  2017年10月02日14:37    【不斷更新】彭博：就在周五　加泰隆尼亞可能宣布獨立
3           3       娛樂  ...  2017年10月02日14:36       好野人！豐臀金么妹走「孕」　砸210萬買童裝
4           4       社會  ...  2017年10月02日14:35  【有片】網紅主播是竹聯大哥妻　因通緝和副堂主夫一併送辦
5           5       政治  ...  2017年10月02日14:35           台灣首辦海洋使徒世界大會　高雄今開幕
6           6       社會  ...  2017年10月02日14:34         批救台盟教小孩說謊　2網紅挨告誹謗結果…
7           7       地產  ...  2017年10月02日14:34          刺激第4季買氣　房仲豁出去要抽iPad
8           8       體育  ...  2017年10月02日14:33        【有片】外卡驟死賽　洋基推新秀對決雙城老將
9           9       社會  ...  2017年10月02日14:33         好心送回收物給老婦賣錢　2清潔隊員遭判刑

[10 rows x 6 columns]

In [97]:
corpus = []
titles = []
for article in news.iterrows():
    corpus.append(' '.join(jieba.cut(article[1]['content'])))
    titles.append(article[1]['title'])
    #print(article[1]['title'])

In [98]:
#corpus[1]

In [99]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
X

<30x3231 sparse matrix of type '<class 'numpy.int64'>'
	with 4140 stored elements in Compressed Sparse Row format>

In [100]:
from sklearn.metrics.pairwise import cosine_similarity
cs = cosine_similarity(X)

In [101]:
cs.shape

(30, 30)

In [102]:
cs

array([[1.        , 0.03578458, 0.02206744, 0.02366243, 0.02479779,
        0.03711632, 0.06421348, 0.07208441, 0.03045552, 0.02731343,
        0.01075331, 0.02562264, 0.01274428, 0.01938159, 0.00897737,
        0.02848501, 0.01704305, 0.02452985, 0.02140347, 0.02299154,
        0.0326164 , 0.02720396, 0.04035877, 0.        , 0.02198997,
        0.03335419, 0.01421242, 0.04347065, 0.0087519 , 0.02281121],
       [0.03578458, 1.        , 0.04513581, 0.04285857, 0.02566572,
        0.08003207, 0.0415381 , 0.0200866 , 0.05178526, 0.01837511,
        0.03338903, 0.10418348, 0.02308308, 0.01404196, 0.02322894,
        0.01965466, 0.03527911, 0.03300492, 0.03138284, 0.02082172,
        0.05677478, 0.09150733, 0.01566425, 0.0720633 , 0.01593174,
        0.12514074, 0.02206479, 0.06998775, 0.02113584, 0.00393493],
       [0.02206744, 0.04513581, 1.        , 0.02454196, 0.08377216,
        0.04155116, 0.02156581, 0.04272216, 0.03953815, 0.01079188,
        0.05735833, 0.04194154, 0.03650682, 0.

In [103]:
titles[6]

'批救台盟教小孩說謊\u30002網紅挨告誹謗結果…'

In [104]:
## argsort
a = np.array([2,7,4,8,9,5])
a.argsort()[::-1]

array([4, 3, 1, 5, 2, 0])

In [105]:
for pos in cs[6].argsort()[::-1][1:10]:
    if cs[6][pos] >= 0.2:
        print(titles[pos],cs[6][pos])

In [106]:
def getSimiliarArticle(articleid):
    print('查詢文章:', titles[articleid])
    for pos in cs[articleid].argsort()[::-1][1:]:
        if cs[articleid][pos] >= 0.2:
            print('相關文章: ',titles[pos],cs[articleid][pos])

In [107]:
getSimiliarArticle(17)

查詢文章: udn售票網休克！陳綺貞粉絲今晚6點重新搶票


In [108]:
getSimiliarArticle(16)

查詢文章: 她挺鄭捷護胖妹　被院長拍桌罵造反
